# Importação

In [3]:
import pandas as pd
import numpy as np
from pathlib import Path

# 9542 (Números absolutos)

In [24]:
df = pd.read_csv("../dados/brutos/9542_2022_brasil_regioes_uf.csv", sep=";", encoding="utf-8", decimal=",", skiprows=5)

print("-----Tabela 9542-----")
df.shape

-----Tabela 9542-----

(1600, 13)

In [26]:
df.columns.tolist()

['Cód.',
 'Brasil, Grande Região e Unidade da Federação',
 'Cor ou raça',
 'Idade',
 'Total',
 'Homens',
 'Mulheres',
 'Total.1',
 'Homens.1',
 'Mulheres.1',
 'Total.2',
 'Homens.2',
 'Mulheres.2']

In [28]:
df.head(10)

,Cód.,"Brasil, Grande Região e Unidade da Federação",Cor ou raça,Idade,Total,Homens,Mulheres,Total.1,Homens.1,Mulheres.1,Total.2,Homens.2,Mulheres.2
0,1,Brasil,Total,Total,162951495.0,78066714.0,84884781.0,151547694.0,72201119.0,79346575.0,11403801,5865595,5538206
1,1,Brasil,Total,15 a 19 anos,14375942.0,7317515.0,7058427.0,14154728.0,7168334.0,6986394.0,221214,149181,72033
2,1,Brasil,Total,20 a 24 anos,15466463.0,7767306.0,7699157.0,15228462.0,7609556.0,7618906.0,238001,157750,80251
3,1,Brasil,Total,25 a 34 anos,30942840.0,15164743.0,15778097.0,30335251.0,14766401.0,15568850.0,607589,398342,209247
4,1,Brasil,Total,35 a 44 anos,32244961.0,15608392.0,16636569.0,30919544.0,14799556.0,16119988.0,1325417,808836,516581
5,1,Brasil,Total,45 a 54 anos,26238693.0,12563500.0,13675193.0,24184186.0,11401234.0,12782952.0,2054507,1162266,892241
6,1,Brasil,Total,55 a 64 anos,21513495.0,10025339.0,11488156.0,19046263.0,8768805.0,10277458.0,2467232,1256534,1210698
7,1,Brasil,Total,65 anos ou mais,22169101.0,9619919.0,12549182.0,17679260.0,7687233.0,9992027.0,4489841,1932686,2557155
8,1,Brasil,Branca,Total,71323919.0,33185762.0,38138157.0,68230928.0,31687364.0,36543564.0,3092991,1498398,1594593
9,1,Brasil,Branca,15 a 19 anos,5610575.0,2796168.0,2814407.0,5545534.0,2754538.0,2790996.0,65041,41630,23411

# 9543 (Taxa de Alfabetização)

In [21]:
df_taxa = pd.read_csv("../dados/brutos/9543_2022_brasil_regioes_uf.csv", sep=";", encoding="utf-8", decimal=",", skiprows=5)

print("-----Tabela 9543 (Taxa)-----")
df_taxa.shape

-----Tabela 9543 (Taxa)-----

(280, 21)

In [29]:
df_taxa.head(10)

,Cód.,"Brasil, Grande Região e Unidade da Federação",Idade,Total,Branca,Preta,Amarela,Parda,Indígena,Total.1,...,Preta.1,Amarela.1,Parda.1,Indígena.1,Total.2,Branca.2,Preta.2,Amarela.2,Parda.2,Indígena.2
0,1,Brasil,Total,93.00,95.66,89.86,97.51,91.20,83.94,92.49,...,89.28,97.54,90.51,85.13,93.48,95.82,90.46,97.48,91.86,82.78
1,1,Brasil,15 a 19 anos,98.46,98.84,98.21,99.11,98.30,93.46,97.96,...,97.58,98.87,97.69,93.46,98.98,99.17,98.92,99.33,98.93,93.47
2,1,Brasil,20 a 24 anos,98.46,98.88,98.23,99.05,98.24,93.48,97.97,...,97.61,98.77,97.63,93.61,98.96,99.17,98.92,99.31,98.87,93.36
3,1,Brasil,25 a 34 anos,98.04,98.75,97.60,98.76,97.59,92.10,97.37,...,96.78,98.52,96.72,92.37,98.67,99.09,98.50,98.97,98.43,91.84
4,1,Brasil,35 a 44 anos,95.89,97.79,94.48,98.30,94.57,86.11,94.82,...,93.10,98.09,93.21,87.18,96.89,98.32,95.96,98.48,95.86,85.06
5,1,Brasil,45 a 54 anos,92.17,95.84,88.73,97.39,89.48,78.18,90.75,...,86.94,97.26,87.74,79.41,93.48,96.54,90.63,97.51,91.11,76.98
6,1,Brasil,55 a 64 anos,88.53,94.06,81.68,96.82,83.87,70.03,87.47,...,80.18,96.83,82.60,71.38,89.46,94.54,83.11,96.81,85.00,68.78
7,1,Brasil,65 anos ou mais,79.75,87.95,67.05,95.97,70.96,53.79,79.91,...,66.97,96.49,71.47,56.91,79.62,87.57,67.12,95.55,70.54,51.27
8,1,Norte,Total,91.84,93.98,88.56,95.46,92.03,81.93,90.99,...,87.62,95.17,91.07,84.25,92.67,94.48,89.72,95.69,92.95,79.57
9,1,Norte,15 a 19 anos,97.77,98.31,97.82,98.84,98.00,90.80,97.19,...,97.19,98.79,97.36,91.11,98.37,98.76,98.59,98.88,98.67,90.48

In [15]:
df_taxa.columns.tolist()

['Cód.',
 'Brasil, Grande Região e Unidade da Federação',
 'Idade',
 'Total',
 'Branca',
 'Preta',
 'Amarela',
 'Parda',
 'Indígena',
 'Total.1',
 'Branca.1',
 'Preta.1',
 'Amarela.1',
 'Parda.1',
 'Indígena.1',
 'Total.2',
 'Branca.2',
 'Preta.2',
 'Amarela.2',
 'Parda.2',
 'Indígena.2']